#!/bin/sh

apt-get update 

apt-get install -y libfreetype6-dev libicu-dev libjpeg62-turbo-dev \
    libmcrypt-dev libpng12-dev libxslt1-dev 

docker-php-ext-configure gd \
    --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ 

docker-php-ext-install gd intl mbstring mcrypt pdo_mysql xsl zip 

apt-get install -y vim git curl net-tools telnet sudo cron

curl -sS https://getcomposer.org/installer | \
    php -- --install-dir=/usr/local/bin --filename=composer

a2enmod rewrite

# Expand default memory limit.
cat <<EOF > /usr/local/etc/php/php.ini
memory_limit = 2048M
EOF

